import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  About,
  Nav,
  Testimonials,
  Footer,
  Header,
  Experience,
  Portfolio,
  Contact,
} from "../components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <About />
      <Experience />
      <Portfolio />
      <Testimonials />
      <Contact />
      <Footer />
    </>
  );
};

export default Home;
